version: "3.9"
services:
  postgres:
    container_name: postgres12
    image: postgres:12-alpine
    restart: example
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
